version: "3.8"
services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/bookdb
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]

volumes:
  pgdata:
